ALTER TABLE users
  ADD COLUMN emailAlertsEnabled BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN campaignAlertsEnabled BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN weeklyReportsEnabled BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN productUpdatesEnabled BOOLEAN NOT NULL DEFAULT FALSE;
